# Generated by Django 5.2.2 on 2025-06-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_alter_contato_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(max_length=1024),
        ),
    ]
