# Generated by Django 5.2.2 on 2025-06-13 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70)),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('data_fabricacao', models.DateField(default=datetime.datetime(2025, 6, 13, 16, 25, 19, 287691, tzinfo=datetime.timezone.utc))),
                ('cor', models.CharField(choices=[('Azul', 'Azul'), ('Vermelho', 'Vermelho'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Preto', 'Preto'), ('Marrom', 'Marrom')], max_length=20)),
                ('imagem', models.CharField(max_length=25)),
            ],
        ),
    ]
