# Generated by Django 5.2.2 on 2025-06-13 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_fabricacao',
            field=models.DateField(default=datetime.datetime(2025, 6, 13, 16, 26, 56, 755884, tzinfo=datetime.timezone.utc)),
        ),
    ]
