# Generated by Django 5.2.2 on 2025-06-20 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_codigo_alter_produto_data_fabricacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='Sem descrição', max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_fabricacao',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 20, 20, 21, 574607, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
