# Generated by Django 5.2.2 on 2025-06-20 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_descricao_alter_produto_data_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_fabricacao',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 21, 2, 11, 126468, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=3, upload_to='produtos/'),
            preserve_default=False,
        ),
    ]
