# Generated by Django 5.2.2 on 2025-06-20 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_data_fabricacao_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_fabricacao',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 21, 2, 54, 624343, tzinfo=datetime.timezone.utc)),
        ),
    ]
