# Generated by Django 5.2.2 on 2025-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('estado', models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('PR', 'Paraná'), ('BA', 'Bahia'), ('RS', 'Rio Grande do Sul')], max_length=2)),
                ('cidade', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('contato', models.CharField(choices=[('C', 'Carta'), ('E', 'E-mail'), ('T', 'Telefone'), ('F', 'Fax')], max_length=1)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nome_usuario', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=256)),
                ('estado_domicilio', models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('PR', 'Paraná'), ('BA', 'Bahia'), ('RS', 'Rio Grande do Sul')], max_length=2)),
            ],
        ),
    ]
